model:
  name: sam2unet
  checkpoint: weights/sam2.1_hiera_base_plus.pt
  config: configs/sam2.1/sam2.1_hiera_b+.yaml
  img_size: 512


experiment:
  name: sam2unet_hu_dice_bce_epoch50_pretrained
  seed: 42

data:
  root_dir: "C:/Users/Hyojun Park/Paper/ct-segmentation/content/data"
  threshold: 0.3

train:
  batch_size: 4
  epochs: 50
  lr: 0.0001
  loss: dice_bce
  save_dir: outputs/sam2unet_dice_bce_epoch50_pretrained
  num_workers: 4
  patience: 10
  use_amp: true

eval:
  visualize: true
