model:
  name: sam2unet
  use_pretrained: true
  checkpoint: weights/sam_vit_h_4b8939.pth  # 사전학습된 SAM ViT-H 모델
  img_size: null

experiment:
  name: sam2unet_hu_dice_focal_epoch50_pretrained
  seed: 42

data:
  root_dir: "C:/Users/Hyojun Park/Paper/ct-segmentation/content/data"
  threshold: 0.3

train:
  batch_size: 4
  epochs: 50
  lr: 0.0001
  loss: dice_focal
  save_dir: outputs/sam2unet_dice_focal_epoch50_pretrained
  num_workers: 4
  patience: 10
  use_amp: true

eval:
  visualize: true
