model:
  name: sam2unet
  checkpoint: weights/sam2.1_hiera_base_plus.pt
  config: configs/sam2.1/sam2.1_hiera_b+.yaml
  img_size: 512


experiment:
  name: sam2unet_hu_dice_focal_epoch50_pretrained
  seed: 42

data:
  root_dir: "C:/Users/Hyojun Park/Paper/ct-segmentation/content/data"
  threshold: 0.3
  normalize_type: sam

train:
  batch_size: 4
  epochs: 100
  lr: 0.0001
  loss: dice_focal
  save_dir: outputs/sam2unet_dice_focal_epoch50_pretrained
  num_workers: 4
  patience: 15
  use_amp: true
  k_folds: 5

eval:
  visualize: true
