model:
  name: utransvision
  use_pretrained: true
  img_size: 224

experiment:
  name: utransvision_dice_focal_epoch50_pretrained
  seed: 42

data:
  root_dir: "C:/Users/Hyojun Park/Paper/ct-segmentation/content/data"
  threshold: 0.3

train:
  batch_size: 4
  epochs: 50
  lr: 0.0001
  loss: dice_focal
  save_dir: outputs/utransvision_hu_dice_focal_epoch50_pretrained
  num_workers: 4
  patience: 10

eval:
  visualize: true
