model:
  name: utransvision
  use_pretrained: true
  img_size: 224

experiment:
  name: utransvision_hu_dice_focal_epoch30_pretrained
  seed: 42

data:
  root_dir: "./src/content/data"
  threshold: 0.3

train:
  batch_size: 4
  epochs: 30
  lr: 0.0001
  loss: dice_focal
  save_dir: outputs/utransvision_hu_dice_focal_epoch30_pretrained
  num_workers: 0

eval:
  visualize: true
